// <auto-generated />
using FotoUPawla20.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FotoUPawla20.Migrations
{
    [DbContext(typeof(CustomModelsContext))]
    partial class CustomModelsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FotoUPawla20.Models.Database.CodliConfiguration", b =>
                {
                    b.Property<int>("CodliConfigurationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConfName");

                    b.Property<string>("ConfValue");

                    b.HasKey("CodliConfigurationId");

                    b.ToTable("Konfiguracja");
                });

            modelBuilder.Entity("FotoUPawla20.Models.Database.KlienciModel", b =>
                {
                    b.Property<int>("KlienciModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdresZdjec");

                    b.Property<int>("Data");

                    b.Property<string>("Email");

                    b.Property<string>("KodKlienta");

                    b.Property<string>("Nazwa")
                        .IsRequired();

                    b.Property<string>("Telefon")
                        .IsRequired();

                    b.Property<string>("Tytul")
                        .IsRequired();

                    b.Property<bool>("Zrealizowano");

                    b.HasKey("KlienciModelId");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("FotoUPawla20.Models.Database.ZdjeciaModel", b =>
                {
                    b.Property<int>("ZdjeciaModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GaleriaId");

                    b.Property<string>("Path");

                    b.HasKey("ZdjeciaModelId");

                    b.ToTable("Zdjecia");
                });
#pragma warning restore 612, 618
        }
    }
}
